LEFT JOIN
INNER JOIN


SELECT P.*, T.NOME 
FROM PACIENTE p 
INNER JOIN TUTOR t ON T.ID_TUTOR = P.ID_TUTOR
WHERE P.ID_TUTOR = 3
				  
SELECT * FROM PACIENTE 

/*exercicios*/

SELECT P.*, T.NOME , T.ENDERECO , T.TELEFONE 
FROM PACIENTE p 
LEFT JOIN TUTOR T ON T.ID_TUTOR = P.ID_TUTOR 


SELECT P.*, T.NOME, T.ENDERECO, T.TELEFONE  
FROM PACIENTE P 
INNER JOIN TUTOR T ON T.ID_TUTOR = P.ID_TUTOR;


SELECT T.*, P.NOME, P.ESPECIE, P.RACA  
FROM TUTOR T 
LEFT JOIN PACIENTE P ON P.ID_TUTOR = T.ID_TUTOR;


SELECT T.*, P.NOME, P.ESPECIE, P.RACA  
FROM TUTOR T 
INNER JOIN PACIENTE P ON P.ID_TUTOR = T.ID_TUTOR;

/*5*/
SELECT m.*, r.DATA_EMISSAO 
FROM MEDICAMENTOS m 
LEFT JOIN ITENSRECEITA i ON i .ID_MEDICAMENTO = m.ID_MEDICAMENTO 
LEFT JOIN RECEITA r ON r.ID_RECEITA = i.ID_RECEITA 

SELECT M.*, IR.QUANTIDADE  
FROM medicamentos M 
INNER JOIN itensreceita IR ON IR.ID_MEDICAMENTO = M.ID_MEDICAMENTO;

/*7*/
SELECT 
FROM receita r
LEFT JOIN AGENDAMENTO a  ON a.ID_AGENDAMENTO = r.ID_AGENDAMENTO 
LEFT JOIN PACIENTE p     ON p.ID_PACIENTE    = a.ID_PACIENTE 
LEFT JOIN ITENSRECEITA I ON r.ID_RECEITA     = r.ID_RECEITA 


SELECT IR.*, P.NOME  
FROM itensreceita IR 
LEFT JOIN paciente P ON P.ID_PACIENTE = IR.ID_ITEM_RECEITA ; 

SELECT IR.*, M.NOME
FROM itensreceita IR 
LEFT JOIN medicamentos M ON M.ID_MEDICAMENTO = IR.ID_MEDICAMENTO;

SELECT r.*, m.*
FROM receita r 
INNER JOIN ITENSRECEITA i ON i ID_RECEITA = r.ID_RECEITA 
INNER JOIN MEDICAMENTOS m ON m.ID_MEDICAMENTO = i.ID_MEDICAMENTO 

